test_documents = [
    "/u/JellyBelly316 (OP) has awarded 1 delta in this post.All comments that earned deltas (from OP or other users) are listed [**here**](/r/DeltaLog/comments/7va64v), in /r/DeltaLog.Please note that a change of view [doesn&#039;t necessarily mean a reversal](https://www.reddit.com/r/changemyview/wiki/index#wiki_what_is_a_.27view.27.3F), or that the conversation has ended.^[Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) ^ ^[Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)",
    "I don&#039;t listen to Joe Rogan, but I think the comparison completely falls apart. Joe Rogan is a successful, good-looking, etc guy. He has a show where he interviews interesting people.     This is called a talk show. It is a very old format. Stephen Colbert has one. Conan O&#039;BRIAN has one. Neil Degrasse Tyson has one. Diane Rehm has one.     Is each one of those people simply &quot;Kim Kardashian&quot;, but for their respective group? Is Diane Rehm simply &quot;Kim for NPR liberals&quot;?    Is Stephen Colbert &quot;Kim for nerds?&quot;.     Others have tried to point out that Kardashian&#039;s entire appeal IS the Kardashians. The reason it is such a vapid show is because you watch the Kardashians because the Kardashians are famous for being watched! I don&#039;t see any of that going on with Joe Rogan. He might be slightly different than my local TV morning show hosts(more famous, etc) but the format is essentially the same. Some chat, some news, some guests.",
    "The idea is to try to explain how Joe Rogan has become the sort of cultural icon that he&#039;s become though. There&#039;s gotta be something there, otherwise all the other podcasts with interesting guests would be just as big ",
    "So, your entire point of view is that his &quot;appeal&quot; is to a demographic very similar to Kardashians?      So their demographic crossover is common people who are shallow? Perhaps average or below average?  By that argument, any popular thing is popular for the same reason as Kardashians.",
    "My point is that people act like Rogan is some sort of deep intellectual that&#039;s value driven and answering the big questions in life. In reality he&#039;s an overexposed celebrity who uses his mainstream appeal to hock overpriced products to his base and regularly reminds his listeners that their day-to-day lives suck",
    "Have you even listened to his podcast? ", "No I&#039;m just guessing", "Wow. ",
    "You have to look at his background for that.  He&#039;s a solid comic and is a commentator for the UFC, both offer a lot of exposure.  He is famous for these two things then for his podcast; his podcast is a result of he&#039;s popularity elsewhere.",
    "So... Kim Kardashian, one of the worst examples in American culture of someone who is all about priding yourself on being pretty, and having no substance.Joe Rogan, a guy who provides a lot of encouragement and insight into how to be healthy. Who is ultra inquisitive and loves talking for extended periods of time to people about different ideas. About what&#039;s wrong with the economy, politics, the environment. Or about advances in science and medicine. About different ideologies and the stigmas about people who do drugs and the sort of mind opening altered perspectives some drugs can give you. He encourages discussion and open-mindedness.Yeah, I&#039;m sure Kim and Joe appeal to people for THE SAME REASONS...",
    "While I agree that Joe&#039;s show gives the appearance of having substance I&#039;d say that&#039;s what makes the parallel with the Kardashians difficult to see initially. But really there isn&#039;t a whole lot there. His understanding of health, nutrition, drugs, society, etc. just isn&#039;t deep enough to do anything more than scratch the surface of these topics or parrot other people&#039;s talking points. Think about how often he talks about the keto diet. Do you think he knows what a ketone is? How metabolism works? How physiological adaptations occur? He talks about this topic so often and with so much authority when really he doesn&#039;t understand its basis in even the simplest sense. So what&#039;s he doing? He&#039;s repeating things he&#039;s heard other people say in different variations over and over and over again. And that&#039;s representative of most of the stuff he talks about.I&#039;m not saying there&#039;s no value there. Obviously people like listening to him. I&#039;m just saying the value isn&#039;t in the content.Think about someone like Sam Harris. His podcast is heavily content-based because he has the knowledge to delve deeply into topics. Joe doesn&#039;t.",
    "[removed]",
    "As I&#039;ve mentioned multiple times in this thread, I like Rogan. I listen to his show all the time and have listened for many years. I don&#039;t think it&#039;s a valuable form of entertainment and ultimately I think his show has done more harm than good. You sound triggered, calm down. ",
    "Dude you are out of your mind?   The only thing you&#039;ve successfully shown in these threads is that you have an axe to grind.   If you don&#039;t think 3+ hour long, in depth discussions on wide ranging topics is not a valuable form of entertainment, then I must ask what is?Joe has the everyman attitude.  He doesn&#039;t claim to know everything and obviously has his own interests.  But he brings in people with a wide range of views and people love it and that&#039;s why he has a viewership that most tv networks would give an arm for.  ",
    "How many times do I have to say I like Joe Rogan? There&#039;s no axe to grind. You can like something and think that it&#039;s mindless entertainment.It&#039;s like when you sit around surfing the internet for 3 + hours. You might get exposed to a variety of things but how much do you really take away from that?=.",
    "You compared him to Kim Kardashian.  I think most reasonable people would call that an insult.  How someone who has seen both programs could even make that comparison is beyond me.  ",
    "I don&#039;t think that&#039;s an insult. They&#039;re both successful and they&#039;re both widely admired. Clearly you all aren&#039;t fans of Kardashian which makes the irony of the parallels between the two even more interesting.",
    "There are a million people who would qualify as successful and widely admired.  You chose to compare him to KK and it wasn&#039;t a compliment.",
    "Sorry, u/dynamostriker19 – your comment has been removed for breaking Rule 2: &gt; **Don&#039;t be rude or hostile to other users.** Your comment will be removed even if most of it is solid, another user was rude to you first, or you feel your remark was justified. Report other violations; do not retaliate. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_2).If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+2+Appeal+dynamostriker19&amp;message=dynamostriker19+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtq0d45/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "&gt;  just isn&#039;t deep enough to do anything more than scratch the surfacePerhaps this is what the entire point is, just like a teacher that introduces you to the beginnings of whatever, and now it&#039;s up to you to pursue it further?",
    "I like this. I don&#039;t know how to give you a triangle but definitely a good point!",
    "Copy/paste ∆ as a lone message I think. But yeah man, I recall my teacher touching on the sinking of the Titanic years before the movie, but years after Robert Ballard discovered the wreck. Obviously he couldn&#039;t touch on everything about that sunken ship in an hour long class. He scratched the surface, and caused me to go to the library, and checkout every Titanic book I could get my hands on. Same thing might happen here, and maybe that&#039;s the expectation. I&#039;m sure you&#039;ve heard the saying, &quot;No one is going to help you until you help yourself.&quot;",
    " ∆",
    "This delta has been rejected. The length of your comment suggests that you haven&#039;t properly explained how /u/temporarycreature changed your view (comment rule 4).DeltaBot is able to rescan edited comments. Please edit your comment with the required explanation.^[Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) ^ ^[Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)[​](HTTP://DB3PARAMSSTART{  &quot;comment&quot;: &quot;This is hidden text for DB3 to parse. Please contact the author of DB3 if you see this&quot;,  &quot;issues&quot;: {    &quot;littleText&quot;: 1  },  &quot;parentUserName&quot;: &quot;temporarycreature&quot;}DB3PARAMSEND)",
    "To do that you can edit your comment to include this symbol:&gt; ∆And give a short explanation (a couple of sentences) of how your view has been changed.After that please report/reply to my comment so that we&#039;d know to send DeltaBot to scan the delta.",
    "Guests like Sam Harris are why alot of us listen. Rogen routinly has on guests who are experts in interesting fields and helps to get their ideas out there. I don&#039;t think most listeners really care about the &quot;macho&quot; factor. It is awesome to randomly hear about something totally different from your own experience from the people on the cutting edge of the research.",
    "I think more than people know they are drawn to Rogan&#039;s traditionally &quot;successful&quot; features than his thoughts and opinions",
    "So your view really isn&#039;t up for debate, since anyone willing to engage in this discussion with you is actually mistaken about their own opinions? I just don&#039;t see how your view can be changed if your view is &quot;people are lying or mistaken in their opinion about something.&quot; That&#039;s not a productive foundation for a discussion since it&#039;s impossible to argue for or against something so subjective.",
    "I’m not.  I listen to Joe Rogan generally for his guests.  I think your missing a big aspect of Rogan - his curiosity. Joe himself is a great interviewer, in my opinion.  I’m not listening to Rogan for his take on health, for example.  I listen to his show when he interviews MDs and PHDs because he asks them the types of questions I would want to ask them and they have to explain it to someone who isn’t an expert in their field. You know who else isn’t an expert in their field?  Me!  If someone like Joe, who isn’t well versed in a subject like physiology has a doctor on his show he asks questions that I might ask - being someone who is also not an expert in physiology, for example, then I get explanations that I can easily understand from experts I don’t have access to.So, I love Joe’s curiosity.  I don’t have access to these people to sit down and pick their brains, but Joe does.  That’s awesome.  So I tend to look for guests on his show that I think have things I’m interested in because I think Joe is genuinely curious and is really good at getting people to open up and explain things well.",
    "I don&#039;t think people are so much drawn to Rogan&#039;s thoughts as much as they are the myriad of guests that he has on.",
    "Why are we only discussing what Joe knows and brings to the conversation? You&#039;re literally ignoring half of the show. Joe admits he doesn&#039;t know much about many of these topics, so he brings on experts and discusses it with them to learn more.The KimK is about her and her family. JRE is about Joe and whoever the guest happens to be. You can&#039;t ignore thatg part of the equation.",
    "&gt; His understanding of health, nutrition, drugs, society, etc. just isn&#039;t deep enough to do anything more than scratch the surface of these topics or parrot other people&#039;s talking points.You&#039;re right. His appeal isn&#039;t necessarily Joe Rogan himself, it&#039;s his guests. Well, some of them. Joe Rogan is a force for good in society because of the fact that he&#039;s open minded enough to host a pretty diverse group of guests. Some of his guests are people who are very well educated and intelligent and experts in their fields. He regularly hosts some of the brightest scientists and millions of people who would otherwise never hear their perspectives are suddenly exposed to a lot of highly educational material thanks to Joe Rogan.You should not compare that to Kim Kardashian.",
    "I fully agree with this sentiment, just last night I watched him interview Jordan Peterson and he really says nothing of substance or asks any insightful questions at all. I do think the comparison with Kardashian is unfounded though. ",
    "[removed]",
    "Sorry, u/dynamostriker19 – your comment has been removed for breaking Rule 2: &gt; **Don&#039;t be rude or hostile to other users.** Your comment will be removed even if most of it is solid, another user was rude to you first, or you feel your remark was justified. Report other violations; do not retaliate. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_2).If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+2+Appeal+dynamostriker19&amp;message=dynamostriker19+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtq0ti3/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "Kim Kardashian, as far as I know, provides viewers with a segway into her private life, which involves examining her business deals, friendships and family dynamics. In addition to this, much of her reality TV is focused around her, and her rise to fame was predicated on a sex tape she released. Joe is completely different. Firstly, and most importantly, his appeal couldn&#039;t be more contrasting. Joe talks about his private life occasionally, but only in relevance to the discussion, whereas KimKs show is really wholly predicated about her and the Kardashian family, Joe dedicates himself to discussions and arguments of ideals, with all sorts of public figures. So in summary, the appeals just aren&#039;t comparable. KimK is about drama, gossip and family life, Joe Rogan is about ideas, argument and discussion. Secondly, Rogan is watched because of his talents as an arguer and comedian. Kim K is famous because of her sex appeal. ",
    "You say Rogan isn&#039;t about drama and gossip but I disagree. His show is filled with drama: the marijuana argument with Steven Pinker, the thrashing he gave Schaub, the weird scoldings he used to occasionally give to Redban and many more examples. It&#039;s also about gossip. Is Amy Schemer stealing jokes? What&#039;s the latest going-ons with Youtube stars (e.g. Aaron Paul)? While Joe doesn&#039;t talk about his family, which is a difference I&#039;ll grant you, he talks about his private life constantly: the vacations he goes on, what happened after the UFC show, his run-ins with random celebrities, etc etc. You might want to say JRE is about discussing ideals but the understanding and discussion of ideals is surface level at best and often wildly off-base. I have a science background and I can tell you anytime Joe touches on a topic I am familiar with he usually doesn&#039;t know what he&#039;s talking about. Thus the discussion of ideals is more about intellectual packaging than it is about an actual search for truth. It&#039;s more about the attempt at being the ideal renaissance man who is as smart as he is athletic than it is about actually diving deep into topics.",
    "Just because &quot;drama&quot; takes place in his podcasts, doesn&#039;t mean its the crux of his show, which is exactly what happens in Keeping up with the Kardashians. No one actually goes to the Joe Rogan experience and follows him, solely to see him be confrontational and/or dramatic. &gt; he talks about his private life constantly: the vacations he goes on, what happened after the UFC show, his run-ins with random celebrities, etc etc.But again, they aren&#039;t the crux of the show. And you&#039;re probably pushing it quite a bit with &quot;UFC after shows&quot; and &quot;celebrity encounters&quot;, this isn&#039;t exactly his private life, and at this point you&#039;re also demanding Rogan&#039;s complete removal of his personal experiences from discussions, which is unrealistic. &gt;  I have a science background and I can tell you anytime Joe touches on a topic I am familiar with he usually doesn&#039;t know what he&#039;s talking about.Honestly, this sort of breaks down when you consider the calibre of the guests he has on his podcasts. He gets acclaimed authors, and professors on who are experts in their field, so if you&#039;re going to say Joe doesn&#039;t make grounded analysis of topics, then you at least have to stipulate his guests do. ",
    "I would say the calibre of guests he has on is really an illustration of how the show is really all about him and his experiences. For example he&#039;ll have Neil DeGrasee Tyson on, who&#039;s a high calibre guest, but he&#039;ll bring him down to his &quot;level&quot; by asking him about the moon landing. I&#039;m not saying he shouldn&#039;t discuss his everyday life, I&#039;m saying the fact that the viewer feels like they&#039;re following through his everyday life and getting the inside insights is what makes the podcast very much like a reality show and is the real appeal. And I disagree that the viewers don&#039;t follow him for the drama. Think about the big 911 show when they had Alex Jones and Eddie Bravo going at it; that was one of the biggest shows Joe&#039;s done. It&#039;s not that crazy, people like drama.",
    "&gt; For example he&#039;ll have Neil DeGrasee Tyson on, who&#039;s a high calibre guest, but he&#039;ll bring him down to his &quot;level&quot; by asking him about the moon landing.Keep in mind it was a 2 hour podcast and that wasn&#039;t all they talked about. But I do recall the argument - if the argument revealed the gaping holes in the moon landing conspiracy theory, or provided a degree of insight into the two sides of the argument, what&#039;s the issue? &gt; Think about the big 911 show when they had Alex Jones and Eddie Bravo going at it;I haven&#039;t watched it, and I certainly don&#039;t plan to with Alex Jones. So I can&#039;t really comment much. I have to ask, was the tone of the podcast dramatic? And would maintain the same line of reasoning for interview shows that interview Alex Jones?",
    "The point is that it&#039;s entertainment but it&#039;s more light drivel than deep insight.",
    "There are enough conspiracy nutjobs (moon landing deniers, flat earthers, etc.), that it becomes an important topic to cover at a shallower level. ",
    "&gt; Steven PinkerI love that you made that mistake, it&#039;s so hillarious to imagine Steven Pinker on the JRE in the first place, but then arguing about weed on top of that :D",
    "The conservative dude guy",
    "Wow, are you psychic? 5 hours after you posted the comment.[Joe Rogan Experience #1073 - Steven Pinker](https://www.youtube.com/watch?v=VUDAdOdF6Zg)",
    "Yeah I know it was just funny",
    "&gt; What&#039;s the latest going-ons with Youtube stars (e.g. Aaron Paul)?*Logan Paul. If you&#039;re gonna argue at least get the most basic facts right.",
    "This comment veers a little too much onto the side of rudeness, I&#039;m just saying. The point wasn&#039;t crucial to his argument, and you make it sound as though it rendered the entirety of his argument redundant. All that was needed was a brief correction. ",
    "No worries. And monkey I wouldn&#039;t be that proud of knowing that guy lol",
    "I barely understand who Logan Paul is but wouldn&#039;t want to conflate him with Aaron Paul a talented actor best knows for Breaking Bad. ",
    "&gt;Similarly listening to the Joe Rogan Experience podcast allows men to live vicariously through Joe. The appeal is not the substance of the show but rather getting a little taste of what it&#039;s like to be Joe Rogan in everyday life. Joe is fit, good-looking, tough, rich, successful a &quot;man&#039;s man&quot; and seemingly intellectual. He may be all of those things but he doesn&#039;t really show any of that. I&#039;ve listened to JRE for a while and I have no idea what his house looks like, what car he drives, I&#039;ve never seen even an hour of his everyday life. I&#039;m mostly listening for his guests. Perhaps it&#039;s because I don&#039;t follow him on social media but even looking at his Instagram it&#039;s mostly stand up promotion, meat and silly stuff. Now compare that to Kim Kardashian&#039;s Instagram account.I do, however, have a better candidate for the title of &quot;Kim Kardashian for Men&quot; - Dan Blizerian, who fits your description perfectly.",
    "Except Kim Kardashian was mainstream famous and most people don&#039;t know who Dan B is",
    "Kim Kardashian has over 103 million followers on Instagram. Dan Blizerian has 23 million. Joe has 3 million.",
    "Damn, I didn&#039;t know Dan Blizerian was that popular",
    "If he were only an Instagram star, perhaps you would have a point, but he has a nearly daily (?) 2-3 hour long podcast, most of which has nothing to do with him or his “success.” If men were looking for a good looking fetishized successful man, they could certainly get it without having to listen to hundreds of hours about DMT and judo. The fact that he is the most successful and prolific interviewer on the Internet can’t be dismissed as “yeah bc he’s got muscles.” Lots of people have muscles; millions of people have more money. Joe brings together comedy, curiosity and self-help very successfully because he is very good at what he does. He has millions of fans because of what he does, not what he has. ",
    "What is he good at exactly? I think he&#039;s a good hype man. A big part of what drew me to him was the way he would hype up UFC fighters when I was still learning the sport. But now that I know the sport his whole act has gotten stale (probably because I now realize it&#039;s barely rooted in truth).",
    "He’s good at interviewing. ",
    "You clearly haven&#039;t listened to a lot of JRE. There are CRAZY amounts of insights given by the guests and Joe himself. I listen to a lot of JRE and claiming I want to live vicariously through him is ridiculous to me. Joe talks about nearly every topic as if he&#039;s well read on it, which gets annoying. You&#039;re just &#039;that guy&#039; who hates JRE because it&#039;s popular and you have some sort of disdain towards Rogans personality. The amount of good and popular guests he has is what really drives the content, not Joe Rogan.  So idk why you&#039;re even focusing on him, everyone goes for the guests, not him. ",
    "I don&#039;t hate JRE, I&#039;m obsessed with it. I just recognize that it&#039;s not a meaningful avenue of content. I also recognize that it&#039;s harmful in a lot of ways but that&#039;s a whole other topic.",
    "&gt;I just recognize that it&#039;s not a meaningful avenue of content. How is an easily accessible, information heavy podcast &quot;not a meaningful avenue of content&quot;?&gt;I also recognize that it&#039;s harmful in a lot of ways but that&#039;s a whole other topic.What&#039;s &quot;harmful in a lot of ways&quot; about his podcast? The fact that you might learn carbs are what&#039;s making you fat, so you change your diet and end up fit and healthy? Is it harmful when Joey Diaz tells a story about farting in different flavors and you laugh your ass off at it? Is it harmful that a well known psychologist like Jordan Peterson helps you figure out a little something about yourself just by listening to him talk to Joe? I&#039;m not entirely convinced your motives for this CMV are entirely genuine. I get the sense there is some deeper meaningless reason that you just hate Joe Rogan.",
    "The fact that you can&#039;t voice criticism towards something without people thinking you have some sort of deep-seated hatred towards it really says something about modern discourse.Rogan does a lot of good. One thing that he does that&#039;s good is promote health and I know that I personally have been encouraged to live a healthier lifestyle because of Joe Rogan. That being said I ultimately think the harm Rogan&#039;s done outweighs the positive.He&#039;s played a pretty big role into bringing conspiracy theories in the mainstream which I would say has hurt the country more than any other modern institutions. Five years ago it would have been unthinkable for a politician to say something like the riots in Charlottesville were a false flag operation. Now we have a climate where politicians can make all sorts of insane inflammatory claims without any sort of attachment to reality and we&#039;ve been conditioned to think that is reasonable. I had never heard a conspiracy theory before I listened to Rogan&#039;s podcast.He helped popularize Alex Jones, a man who makes money off his followers off the backs of dead children.He&#039;s consistently sold his followers snake oil.He&#039;s popularized a form of pseudoscience which has no regards for the truth.He probably played a role in the election of Donald Trump. I know I know, he totally insists he&#039;s completely in the middle and he&#039;s not for one side or the other. But I heard Hillary Clinton killed someone. Remember that? How many times before the election did he repeat crazy conspiracy theories about her murdering people she didn&#039;t like or her being on the verge of death, etc. etc. And Trump is bad too........but WHAT IF he got into office and it turned out to all be a rouse and he&#039;s actually really competent?!? I&#039;m not for one side or  the other.......but Jeff Ross met Donald Trump once and said he was completely reasonable!Rogan&#039;s done more to hurt modern discourse than most people realize.",
    "I dislike Joe Rogan for the people he choses to platform, and relatively uncritically so, and because sometimes he has a very overconfident attitude.    In the podcast episodes I have listened to I didn&#039;t hear him talk much about his lifestyle or talk from the perspective of it. Vloggers and Streamers would be a much better example of selling lifestyle and carelessness, unless you view being able to interact with celebrities as the ultimate tip of lifestyle.    I agree, there is a ton of people that legit started to worship personalities similar to him as role models, but that is more of a consequence of what appeal he already has to them. And considering that its a podcast that engages with ideas this appeal is probably just a superficial one.    Overall I dont think the Kim Kardashian comparison does much good. If you want to criticize him effectively you should engage with the content and interviewing style.",
    "Good points, I agree with almost everything you said.", "And has it changed you mind? ", "Not really",
    "If you agree with me saying that Joe Rogan is not the Kim Kardashian for guys, and that the comparison is also not useful, then I am not sure how one could challenge your view any further.    Do you want to elaborate on your original post so that people can keep trying?",
    "Obviously any podcaster is going to spend some time hyping himself up and selling his persona and lifestyle so that people start to care to listen to what that person has to say.That being said, on a weekly basis Rogan interviews *professionals* from a wide variety of disciplines (could be anywhere from genetic research to astrophysics to martial arts to clinical psychology).  During these *multiple hours* long (usually around 2.5 hours) interviews, Rogan does a great job asking inquisitive questions without dominating the conversation thereby allowing these incredibly knowledgeable people to provide the information and wisdom they&#039;ve accumulate through decades of work in their fields.The main reason to listen to the JRE is not for Rogan but actually his *guests*.Tell me again how this is in any way similar to the vapid materialism that is Kim Kardashian.",
    "Sometimes he does. Other times he&#039;s dominating, dismissive, argumentative and loud. ",
    "I think you misunderstand the appeal of Joe Rogan, because Joe himself is mainly a springboard for interesting conversations with interesting people. It doesn&#039;t even require you to particularly like Joe Rogan. Is there some non-zero amount of people who want to live vicariously through him? Probably. But in general, there doesn&#039;t seem to be any reason to presume some alternate motive to his appeal when the face value explanation holds up.",
    "Ok but isn&#039;t a little reality-show-esque that people who watch his show know all of his friends, know what he&#039;s up to almost all the time and know his personality well enough to speak on behalf of him on forums.",
    "Knowing his personality is a natural result of watching him have lots of conversations. And his friends are mostly successful comedians. It&#039;s not weird that people who watch a Joe Rogan program have an interest in people like Joey Diaz, Ari Shaffir, Bert Krescher, etc. It&#039;s not like the face value appeal of funny people talking about stuff fails to explain the appeal of the show.",
    "&gt;Ok but isn&#039;t a little reality-show-esque that people who watch his show know all of his friendsI think with this comment you admitted to the fundamental difference between the Kardashians and JRE. The &quot;reality-show-esque&quot; comment you made leads me to believe that you know full well that it is a talk show that occasionally contains reality show elements. Whereas the Kardashian show is exclusively a &quot;reality show&quot; with no content other than &quot;reality&quot;, and I use that term loosely.I&#039;m not a big Joe Rogan fan, nor do I listen to the podcast often, but I can safely say while I may not have learned  much from JRE, I certainly have never learned anything from the Kardashian show.",
    "Now you&#039;re conflating watching a podcast with a fan community. I can watch his podcast and enjoy some of the episodes when he has interesting guests without being a fan of Rogan himself. Further, his podcasts can be really informative and enlightening, dependent on the guests. I don&#039;t see what kind of unique information I could learn about history or philosophy from watching a few episodes of The Kardashians in the way I can from watching a few episodes of Rogan&#039;s podcast.",
    "Name something you didn&#039;t know before that you&#039;ve learned from a Rogan podcast",
    "Dr. Rhonda Patrick is a biochemist who is incredibly informative about health and diet. So that&#039;s one example.",
    "If 1% of his show were about his personal life, his fans would know about his personal life. That they know some things about him does not support your claim.",
    "I usually listen to hear what his guests have to say, if the guest seems interesting, ill download and listen to the podcast, otherwise i will not. I know that i cannot say i listen to it for this reason and therefore that&#039;s why others do too.Everyone will tune in for their own reasons, but a blanket statement saying that the only reason people listen to his podcast is because of x doesn&#039;t really encompass the thousands different of people that listen to him, and their motives for doing so.Also, i know several women who listen to his podcast too. So not sure what to make of that using your perspective. ",
    "Strongest points I&#039;ve seen so far. I&#039;m sure there&#039;s a wide variety of reasons people listen to the show considering how large his viewership is. Maybe it would be more accurate to say it&#039;s a common theme among a big portion of his listeners. And you&#039;re right it definitely doesn&#039;t apply to the female listeners.By the way I&#039;m new here. What&#039;s all this stuff about rewarding a triangle and whatnot?",
    "Without being inside of the heads of the &quot;big portion of listeners&quot;, it&#039;s pretty much impossible to know. You can ask listeners why they listen and hope they are truthful, but other than that you can&#039;t really know the truth of it so I don&#039;t really know what it would take to change your view. I&#039;m a listener don&#039;t listen for drama, I listen because I think Joe is funny, I think he has a variety of interesting guests and he asks them good questions that in my opinion lead to interesting conversations and answers. ",
    "That&#039;s true, it&#039;s unknowable. So this is all just speculation.",
    "&gt;By the way I&#039;m new here. What&#039;s all this stuff about rewarding a triangle and whatnot? When someone has partially or completely changed your view, you can reward the applicable comment by replying with `!delta`Edit: yeah, yeah, deltabot, I know. ",
    "This delta has been rejected. You can&#039;t award OP a delta.Allowing this would wrongly suggest that you can post here with the aim of convincing others.If you were explaining when/how to award a delta, please use a reddit quote for the symbol next time.^[Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) ^ ^[Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)[​](HTTP://DB3PARAMSSTART{  &quot;comment&quot;: &quot;This is hidden text for DB3 to parse. Please contact the author of DB3 if you see this&quot;,  &quot;issues&quot;: {    &quot;op&quot;: 1  },  &quot;parentUserName&quot;: &quot;JellyBelly316&quot;}DB3PARAMSEND)",
    "From what i gather (new here as well) if someone has managed to change your view, you award them a delta/triangle. Not sure how it is done and all that though!",
    "this might be one of the worst CMV I have seen in a long time.  First, Joe is not &quot;good looking, wtf?  He&#039;s a professional standup, broadcaster, is black belt in bjj, has the #1 podcast in the world with no ad polution, and the list goes on. appearance of substance?  he gets balls deep in nutrition, bow hunting, martial arts, astronomy etc with the worlds leading experts.   i hate to be the guy defending rogan, but you are the one lacking substance OP :[",
    "I know a lot about nutrition and I can tell you he definitely doesn&#039;t get &quot;balls deep&quot; into it. He has a rudimentary understanding of biochemistry. I appreciate the overall sentiment though",
    "whats your sentiment on JR having steven pinker on today?  where does that piece fall in your terrible analogy? ",
    "Do you mean Steven Crowder? Wasn&#039;t a fan of the episode. I don&#039;t like overly partisan people",
    "I watch Joe Rogan because of the people and interesting conversations he has with people. I don&#039;t consider him good looking. I don&#039;t want to look like him. I don&#039;t want to be like him whatsoever. I want to be like me.I like his content though.",
    " ∆",
    "This delta has been rejected. The length of your comment suggests that you haven&#039;t properly explained how /u/WhyAmIACunt changed your view (comment rule 4).DeltaBot is able to rescan edited comments. Please edit your comment with the required explanation.^[Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) ^ ^[Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)[​](HTTP://DB3PARAMSSTART{  &quot;comment&quot;: &quot;This is hidden text for DB3 to parse. Please contact the author of DB3 if you see this&quot;,  &quot;issues&quot;: {    &quot;littleText&quot;: 1  },  &quot;parentUserName&quot;: &quot;WhyAmIACunt&quot;}DB3PARAMSEND)",
    "[removed]",
    "I watch Rogan all the time and like him. Just trying to explain why I and so many others like him (why he&#039;s the cultural icon that he is)",
    "I must do a bad job of conveying tone in my messages. Not angry. Also breathing fine. ",
    "Sorry, u/nate725 – your comment has been removed for breaking Rule 2: &gt; **Don&#039;t be rude or hostile to other users.** Your comment will be removed even if most of it is solid, another user was rude to you first, or you feel your remark was justified. Report other violations; do not retaliate. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_2).If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+2+Appeal+nate725&amp;message=nate725+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtpz31b/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "[removed]",
    "Sorry, u/MCEngraver – your comment has been removed for breaking Rule 2: &gt; **Don&#039;t be rude or hostile to other users.** Your comment will be removed even if most of it is solid, another user was rude to you first, or you feel your remark was justified. Report other violations; do not retaliate. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_2).If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+2+Appeal+MCEngraver&amp;message=MCEngraver+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtpzvmz/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "I kinda get where you&#039;re coming from - but no one would watch a show following Joe Rogan around in his everyday life.People might *like* Joe because he seems to be living a balanced and enviable lifestyle - but that&#039;s not why they listen to his show. They listen because the show *does* have substance. He interviews interesting people - not celebrities, but people with legitimately interesting subjects to cover. Like - he had Mel Gibson on with a stem cell doctor to spend an hour and a half talking about stem cell therapy (which the doctor has done for Gibson). They didn&#039;t even mention Gibson&#039;s career and he wasn&#039;t there to plug anything. He was there to bring attention to the conversation about stem cell therapy.",
    "I loved when he talked to James Hetfield of Metallica about bees for an hour.   I learned a lot about bees.  ",
    " ∆",
    "This delta has been rejected. The length of your comment suggests that you haven&#039;t properly explained how /u/MCEngraver changed your view (comment rule 4).DeltaBot is able to rescan edited comments. Please edit your comment with the required explanation.^[Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) ^ ^[Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)[​](HTTP://DB3PARAMSSTART{  &quot;comment&quot;: &quot;This is hidden text for DB3 to parse. Please contact the author of DB3 if you see this&quot;,  &quot;issues&quot;: {    &quot;littleText&quot;: 1  },  &quot;parentUserName&quot;: &quot;MCEngraver&quot;}DB3PARAMSEND)",
    "But there&#039;s a million podcasts out there that bring on equally interesting guests that don&#039;t have a similar fanfare. The difference is Rogan himself.",
    "Yea, because Rogan is skilled at framing the experts&#039; subject matter in a way that becomes interesting to people with no background in it.You say he&#039;s &#039;seemingly intellectual&#039;, implying he doesn&#039;t know what he&#039;s talking about - and that&#039;s the entire point. He asks the basic, even dumb questions that give his listeners an entry way into very complex and interesting subjects.",
    "Sure, &quot;framing the experts&#039; subject matter..&quot;Expert: &quot;....so that&#039;s why the heritability of Type II diabetes is actually stronger than the heritability of type I!:Joe: &quot;.......&quot;Expert: &quot;.....&quot;Joe: &quot;......&quot;Expert: &quot;......&quot;Joe: &quot;The crazy thing about DMT is you make it before you die....&quot;",
    "Yikes, show us on the doll where Joe Rogan touched you...That’s simply not an accurate representation of his interview style, which is probably why you’re confused about the reason he’s the most popular podcast interviewer of all time.",
    "Joe Rogan did not molest me. ", "[removed]", "[removed]",
    "Sorry, u/nicholas_12 – your comment has been removed for breaking Rule 3: &gt; **Refrain from accusing OP or anyone else of being unwilling to change their view, or of arguing in bad faith**. Ask clarifying questions instead (see: socratic method). If you think they are still exhibiting poor behaviour, please message us. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_3).  If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+3+Appeal+nicholas_12&amp;message=nicholas_12+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtpyhm6/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "Nice, I appreciate the attempt",
    "It&#039;s anecdotal, but Rogan is one of the main reasons I stopped being a degenerative, fat, lazy high school drop out and pursued higher aspirations and am now a college grad &amp; nationally certified as a clinical lab tech - and can now run a sub-20 min. 5k (actually probably can&#039;t do this anymore but I was able to less than a year ago lol). I promise you that you&#039;ll find 0 people who Kim had this ability to influence.",
    " ∆That&#039;s awesome, glad to hear it&#039;s had a positive effect on you!I wonder if Kardashian&#039;s show has helped people change their lives.",
    "I highly doubt it - Kim K is purely entertainment, whereas JR is definitely entertainment but it&#039;s tough to not take some educational, philosophical, and inspirational aspects away from a lot of what he has to say.",
    "Confirmed: 1 delta awarded to /u/JakeAndJavis ([1∆](/r/changemyview/wiki/user/JakeAndJavis)).^[Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) ^ ^[Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)[​](HTTP://DB3PARAMSSTART{  &quot;comment&quot;: &quot;This is hidden text for DB3 to parse. Please contact the author of DB3 if you see this&quot;,  &quot;issues&quot;: {},  &quot;parentUserName&quot;: &quot;JakeAndJavis&quot;}DB3PARAMSEND)",
    "Sorry, u/JakeAndJavis – your comment has been removed for breaking Rule 3: &gt; **Refrain from accusing OP or anyone else of being unwilling to change their view, or of arguing in bad faith**. Ask clarifying questions instead (see: socratic method). If you think they are still exhibiting poor behaviour, please message us. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_3).  If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+3+Appeal+JakeAndJavis&amp;message=JakeAndJavis+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtpy3bn/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "Joe rogan often talks about way more intelligent shit than Kim kardasian could even imagine. ",
    "I don&#039;t know how smart Kim K is because of how controlled her show is but I don&#039;t think it&#039;s necessarily true that she&#039;s dumb. Just because Joe discusses a lot of stuff doesn&#039;t mean that he&#039;s smart.",
    "He&#039;s smart enough to have expert guests that generate worthwhile discussions. ", " ∆",
    "This delta has been rejected. The length of your comment suggests that you haven&#039;t properly explained how /u/RagingNerdaholic changed your view (comment rule 4).DeltaBot is able to rescan edited comments. Please edit your comment with the required explanation.^[Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) ^ ^[Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)[​](HTTP://DB3PARAMSSTART{  &quot;comment&quot;: &quot;This is hidden text for DB3 to parse. Please contact the author of DB3 if you see this&quot;,  &quot;issues&quot;: {    &quot;littleText&quot;: 1  },  &quot;parentUserName&quot;: &quot;RagingNerdaholic&quot;}DB3PARAMSEND)",
    "This makes no sense.Kardashian is a self-involved, vapid media whore who rose to fame by banging a rapper.  That&#039;s about the extend of it.  Gee, what a shining example.  She contributes absolutely nothing valuable or positive to society, and is arguably a detriment. I will concede that Rogan can be a bit of a dude-bro, but many of the podcasts are genuinely interesting discussions of real and important topics with highly esteemed guests.  And that&#039;s why I listen (cherry pick, really), **for the guests**.  I would (and do) watch those guests on *any show*, Joe&#039;s just happens to be a very popular one that attracts these guests. How much have you actually listened to the show to draw this conclusion?  Are you actually listening or just watching skin deep and deciding this based on seeing a built bald dude?    ",
    "I&#039;ve been watching the show for about 7ish years regularly",
    "Kim Kardashian is only famous because she sucked a dick. Where as Joe Rogan got famous from fighting in MMA, hosting fear factor and being a comedian. He’s actually had to work at what he’s got where she just got on her knees. ",
    "He&#039;s never fought in MMA. And actually she probably worked harder for what she had than he did. She at least had the initiative to make a sex tape. He basically got super lucky and got picked for a 1 in 1,000,000 spot",
    "And he was already a comedian before he got picked for fear factor. ",
    "He was a struggling comedian before got picked up for News Radio which is luck more than anything.",
    "That’s how being a comedian works. Almost every comedian out there will tell you they spent years telling jokes at open mic nights or some other lowly bar before they got a deal. Kardashian literally got famous for sucking 1 dick and recording it. ",
    "&gt; He was a struggling comedian before got picked up for News Radio which is luck more than anything.What has that got to do with the content of the show? And how does that relate to your initial point?You’re grasping at straws",
    "Which part of his career do you think was him just getting lucky in a way that is materially different from other entertainers? If you were arguing Howard Stern is analogous to the Kardashians I&#039;d see you having some sort of point. Rogan, however introduces me to interesting people that I can look more into after their interview with him if I want to. I feel his role as a popularizer of ideas is what makes his show so interesting. ",
    "Are you shittin&#039; me?She&#039;s &quot;&quot;&quot;&quot;famous&quot;&quot;&quot;&quot; by proxy of banging someone who was famous.  Forgive me if I don&#039;t laud her accomplishments for being born to an already-famous family, as a voluptuous woman who can get a dick by snapping her fingers. Joe was worked at his success.  He&#039;s an accomplished comedian, martial artist and TV presenter.  Yes, he was lucky to be noticed by a talent manager.  So what, luck is the largest factor in any major success. The difference is: his luck wouldn&#039;t have occurred had he not worked towards it.  Her luck was just being fucking born. ",
    "Yes he did fight in MMA he just fought as an amateur not for UFC. ", "[removed]",
    "Sorry, u/RagingNerdaholic – your comment has been removed for breaking Rule 5: &gt; **Comments must contribute meaningfully to the conversation**. Comments that are only jokes or &quot;written upvotes&quot; will be removed. Humor and affirmations of agreement can be contained within more substantial comments. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_5).If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+5+Appeal+RagingNerdaholic&amp;message=RagingNerdaholic+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtq2lv6/)+because...).",
    "Kim Kardashian and her entire family owe their fortunes to Kim Kardashian fucking someone on camera. Joe actually worked hard to get where he is. ",
    "I&#039;ve said this multiple times already but he got lucky to get picked to be on TV",
    "He had already been doing stand up comedy for 14 years when he got &quot;Just shoot Me&quot;. Driving your ass from gig to gig across the country is rough work. Joe did it. Meanwhile, Kim made a porn vid and now she and her entire family are famous. ",
    "I don&#039;t think joe rogan qualifies as attractive on the internet scale, but even in real life he is maybe average. I think if guys were looking for someone to emulate they would choose someone a little more blatantly successful, but maybe I have different values then them. ",
    "He definitely used to be much more attractive but even now he&#039;s jacked and I&#039;m sure he&#039;s propositioned by 10s on a regular basis. I applaud your values but just so you know, Rogan is immensely successful. He&#039;s a part owner of a supplement company, a commentator for a major sports brand, he sells out arenas for his comedy shows and his podcast gets millions of downloads per month.",
    "He is famous and successful, but it’s more due to his actions and accomplishments than due to his big ass.  He has on doctors and scientists, and while they usually discuss things that Joe has interest in, I don’t think that the way you’re framing his show is at all representative.  Why would you host a show discussing topics you didn’t find interesting?KK is a bimbo saying ‘ooh look at me’ with zero additional substance.  Even if Joe’s views on bigfoot are childish and a bit silly, he probably does have a positive role in getting people to see the sillyness in their own beliefs sometimes.  He also has extreme athletes in and often discusses how they keep motivated and what drives them.  He’s trying to share that drive with his audience, which is a good thing.Anyway if you’re interested in the topics he discusses on his show, you’ll find them very thought provoking.  If not, there’s a good chance you’ll at least laugh.  I dont think you could say the same for KK..Kind of a silly comparison, really...",
    "It&#039;s not really due to his actions and accomplishments. He got picked for a TV show which is more luck than anything else. ",
    "Right, a successful stand-up comic getting picked for a job is pure luck.  Maybe you’ll get picked up next!!!",
    "He wasn&#039;t successful before News Radio. I&#039;m not saying he wasn&#039;t talented. I&#039;m saying that with the sheer number of people who want to be on TV getting picked is always luck",
    "Depends on what ‘is is’?He had been making a modest living as a comedian for several years by that point, and had multiple offers from major networks (one of which he accepted and did several episodes) before news radio.It’s not an easy living.  Not that many people can commit to that lifestyle and prove their value while getting by on scraps.  It would have been far easier to take a job in construction or whatever, but he stuck it out.  He proved his talent and commitment and eventually caught an opportunity.  Call that luck if you want?  I don’t really think so.It’s all good though; I’m not too worried about it, if you think he’s just a meathead; to each his / her own...",
    "I don&#039;t think he&#039;s just a meathead. I think he&#039;s worked very hard and has talent. But 99.9% of the people who work hard and have talent don&#039;t make it in entertainment ",
    "So...kim kardashian?  Who is famous for literally sucking dick and having a fat ass?I mean...your argument is so absurd that I don’t even know what to say...they’re clearly at different levels of talent, different levels of effort, different levels of ‘useful for or society,’ have a way different kind of respect from their fanbase and...the only similarity is that they’re both on the tele...I mean, get outta town, that’s crazy.*sigh*",
    "[removed]", "That would honestly be awesome",
    "Sorry, u/usafmech11 – your comment has been removed for breaking Rule 1:&gt; **Direct responses to a CMV post must challenge at least one aspect of OP’s stated view (however minor), or ask a clarifying question**. Arguments in favor of the view OP is willing to change must be restricted to replies to other comments. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_1).  If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+1+Appeal+usafmech11&amp;message=usafmech11+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtpxra4/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).Sorry, u/usafmech11 – your comment has been removed for breaking Rule 2: &gt; **Don&#039;t be rude or hostile to other users.** Your comment will be removed even if most of it is solid, another user was rude to you first, or you feel your remark was justified. Report other violations; do not retaliate. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_2).If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+2+Appeal+usafmech11&amp;message=usafmech11+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtpxra4/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "Hmm i only listen to Joe Rogan’s podcast to hear what the other person has to say. Joe could mute his microphone for all i care... ",
    "And if you do that you will notice that regardless of who is on and what their background is, the conversation almost always goes to one of what I would call the &quot;Rogan topics&quot;. He could have on a record-setting champion beekeeper and you know a good portion of the time is going to be spent talking about DMT, MMA gloves, social justice warriors, Hillary Clinton or one, if not multiple, of the many other &quot;Rogan topics.&quot; In doing so the podcast stays about Rogan.",
    "I literally have never heard the phrase “MMA gloves” and I listen to the JRE at least once a week. I never listen to the episodes with comedians (unless it’s one I know and like) or MMA fighters... DMT comes up a lot, social justice warriors pop up a lot (but normally the guest brings it up), Clinton is mentioned at least as much as trump... and paleo/keto/meat-heavy diets is talked about a lot... But like that other guy said, I pick episodes based on the guest. Joe doesn’t really do much for me. ",
    "&quot;Normally the guest brings it up&quot;.Nah, Joe&#039;s the one who brings it up just about all the time. He&#039;s obsessed with SJWs which, by the way, is something that I almost never hear of being brought up outside of his show. It&#039;s part of the meaningless drama he conjures up which I think parallels the Kardashians. ",
    "You&#039;ve definitely heard him talk about MMA gloves. Like how the pride gloves were curved so you don&#039;t get eye pokes. He&#039;s talked about that at least 50 times.",
    "The last 2 episodes I listened to were Michael Shermer and Jordan Petersen and I’m pretty sure they both said “social justice warrior” before joe did",
    "&gt; The success of his podcast and his brand is just another form of celebrity worship, and is more about that than about content.Can you give an example of *legitimate* celebrity then? Joe was a professional comedian going [back to the 1980s](https://en.wikipedia.org/wiki/Joe_Rogan) right up through Netflix comedy specials in 2013 and [2016](https://www.netflix.com/ca/title/80117443). He is a [professional actor](http://www.imdb.com/name/nm0736579/) going back to early 1990s right up through 2015, became known on TV sitcom &quot;NewsRadio&quot; with Phil Hartman, Dave Foley, and Andy Dick. He was host of the popular reality show &quot;Fear Factor&quot;, and has been a UFC promoter as well.Among these things, he has his long-form interview podcast that is 3-hours long episodes, akin to Larry King and other long-form interviewers.Despite all of that work across fields of entertainment for decades, you think of him in terms of &quot;celebrity worship&quot; rather than content. What exactly does one have to do in the multiple fields of entertainment to be a legitimate celebrity, in your mind?By way of comparison, [Kim Kardashian](https://en.wikipedia.org/wiki/Kim_Kardashian) became famous because she was a wealthy socialite and due to her sex tape with Ray J. That she was known to people was leveraged to do a reality show that included her and her family. Her celebrity status isn&#039;t based on any actual art forms. She&#039;s didn&#039;t get famous from work as a comedian, actress, singer, promoter, or other things that require talent and effort. She is mostly famous for being famous, seeded by a sex tape and social status from her family&#039;s wealth, and everything else has fallen out of that start, and keeps going because of it.So no, I don&#039;t buy your comparison. Joe is a professional entertainer, has spent decades at it, honed his talents, and works hard at providing quality entertainment that includes very interesting interviews. We don&#039;t just follow Joe around town buying clothes, working out, or doing &quot;Joe&quot; stuff.What does Kardashian actually do other than *be* Kim Kardashian?",
    "Would you make the same claim about ANY goodlooking, successful, macho guy who has a talk show or podcast? By your logic, an 140 pound nerd who has on the exact same guests with the exact same topics has &quot;sophisticated&quot; listeneners who listen for the content, because guys don&#039;t envy the host himself. It seems like you&#039;re taking superficial traits alone and claiming people listen for superficial reasons. Kind of tautological, if not hypocritical.",
    "If Rogan was a 140 pound nerd he wouldn&#039;t be the cult figure that he is today",
    "I have never listened to this podcast but it seems like you hate this guy for some reason. He seems like he invites conversation from many sides and viewpoints and I appreciate that. I have also never seen the Kardashian’s show but I understand it is not good for society. I think that they differ in many levels as an outsider. Rogan talks about important issues while Kim slobs in knobs. Big difference. ",
    "I&#039;m not sure where people are getting the idea that I hate him", "Your comments mostly",
    "I listen to Joe Rogan for his guests and his interview style. He has these meandering 3 hour casual conversations with the most interesting people, some of whom I never would have heard of without his podcast. For instance, Zach Leary, or Will MacAskill. These are guys who I never would have heard of without JRE but I enjoyed their conversations immensely. Then there’s people like Sam Harris, Jordan Peterson etc. who are good to hear on Rogan because the casual, friendly tone of the show brings out interesting tangents in their line of thinking. Meanwhile comedy fans, health nuts, and avid MMA fans are also attracted to JRE for the other guests that I tend to skip over. Rogan has broad tastes, so a broad amount of people enjoy his broad variety of guests. Kardashian is not nearly as diverse and is an unlikely gateway to discover interesting new intellectual conversations.",
    " ∆",
    "This delta has been rejected. The length of your comment suggests that you haven&#039;t properly explained how /u/thethinkingpreacher changed your view (comment rule 4).DeltaBot is able to rescan edited comments. Please edit your comment with the required explanation.^[Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) ^ ^[Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)[​](HTTP://DB3PARAMSSTART{  &quot;comment&quot;: &quot;This is hidden text for DB3 to parse. Please contact the author of DB3 if you see this&quot;,  &quot;issues&quot;: {    &quot;littleText&quot;: 1  },  &quot;parentUserName&quot;: &quot;thethinkingpreacher&quot;}DB3PARAMSEND)",
    "[deleted]",
    "Does he though? It seems like he brings on a lot of fringe scientists like the dude who talks about ancient civilizations. Or like Rhonda Patrick who talks about animal research like its clinical research, realizing most people won&#039;t be able to understand the difference.",
    "[deleted]",
    "It&#039;s more that he doesn&#039;t have the tools to evaluate the theories and essentially just ends up parroting what the fringe scientists tell him",
    "[deleted]",
    "His insistence that keto is supreme. His insistence that psych meds are bad. His insistence that hollywood culture is shallow and ego-driven when he is hollywood culture. His insistence that working people should quit their 9-5 jobs and start podcasts.",
    "Yes, he brings many many different guests.Some of the most “legit” ones being, Neil Degrasse, Sam Harris, Brian Cox, Jordan Peterson, Lawrence Krauss",
    "&gt; The appeal of Kim Kardashian was that she was rich, attractive and successful. This is false. I listen to his his podcast sometimes, but I&#039;m not even aware he&#039;s rich, attractive, or successful. I mean, I guess he is in the sense that most celebrities are rich. But I just don&#039;t think of him as rich. I certainly don&#039;t want to be him. I&#039;d much rather be some of the people he has on his podcast. I know that&#039;s anecdotal, but I don&#039;t know what it would take to change your view; it&#039;s not like there are polls on this subject. What reason have you to believe that is the appeal of Joe Rogan? You didn&#039;t make an actual argument, only an assertion. ",
    "So you&#039;ve never listened to his podcast. Probably never seen him on his news radio days. Never heard is stand up. Watched his great hosting on fear factor.The man is multi talented. His humor comes from a place of intelligence, which translated wonderfully to his podcast. It is thought provoking, he gets great guests, and continues to stoke thought among listeners.So yeah...he&#039;s exactly like a Kardashian. Because they are multi talented. Mostly at plastic surgery, photo shop, marrying deservedly famous people, and sexual positions. ",
    "I think your view is a very sexist view and reading through the comments on here, I have not seen an arguement that Joe Rogan is not even close to what Kim Kardashian has achieved and accomplished.  The amount of success, fame and wealth that she has accumulated.  It seems to me like everyone is agreeing that Kim Kardashian is not deserving of admiration.  I would posit the view that Kim, is not remotely close to where Joe Rogan is and he would have to travel many more miles before he gets in the vicinity.",
    "That’s a very broad-brush take on JRE.If you are just listening to him talk shit with his buddies then yeah I agree.But he is a genuinely good interviewer. It depends who he has on the show. I’ve gained a lot of knowledge from finding guests from the show.A few who come to mind; Andreas Antonopoulous, Jordan Peterson, Graham Hancock, John Anthony West, Duncan Trussell, Christopher Ryan etcNothing comparable can be said of the Kardashians.",
    "[removed]",
    "Sorry, u/Commander_Idnarb – your comment has been removed for breaking Rule 1:&gt; **Direct responses to a CMV post must challenge at least one aspect of OP’s stated view (however minor), or ask a clarifying question**. Arguments in favor of the view OP is willing to change must be restricted to replies to other comments. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_1).  If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+1+Appeal+Commander_Idnarb&amp;message=Commander_Idnarb+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtpvuis/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "I&#039;m sure that there are some people who like Rogan for the exact reasons you lay out.  There is obviously a desire for people to act this way because there are people who are famous for the exact reasons you point out.For me personally though, I like Rogan because he does long form interviews with people where he allows them to state their case, and he doesn&#039;t try to misinterpret what they say, and he doesn&#039;t try to shoot down an idea he disagrees with by strawmanning.  He&#039;ll make an attempt to understand their actual argument and he&#039;ll deal with the argument on the terms of the person providing the argument.  He&#039;s not always good at doing this, but he does make the attempt, and more often than not it provides a thoughtful few hours of talk radio where odd ideas are entertained. ",
    " ∆",
    "This delta has been rejected. The length of your comment suggests that you haven&#039;t properly explained how /u/soupvsjonez changed your view (comment rule 4).DeltaBot is able to rescan edited comments. Please edit your comment with the required explanation.^[Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) ^ ^[Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)[​](HTTP://DB3PARAMSSTART{  &quot;comment&quot;: &quot;This is hidden text for DB3 to parse. Please contact the author of DB3 if you see this&quot;,  &quot;issues&quot;: {    &quot;littleText&quot;: 1  },  &quot;parentUserName&quot;: &quot;soupvsjonez&quot;}DB3PARAMSEND)",
    "I don&#039;t know jack about him except his podcast - I hate wrastlin&#039; and boxing so grain of salt to all that stuff but for the podcast:I enjoy it and am glad it exists but it&#039;s important, for me, to remember that Joe is a sponge.  It&#039;s good and bad - he believes a lot of stuff, initially, that appears correct on the surface even if it&#039;s wrong, but he&#039;s also very willing to let in new and outside ideas.  Seriously too - actually consider them instead of playing off them for a joke or a comeback.If he didn&#039;t ask on obvious theatrical concern trolls like faux leftists and manipulative ideologues who slither in the auspices of civil discourse his show would be less of an oddity and more of a staple of American pop culture media.  2cents anyway",
    "[removed]", "This is my favorite response",
    "Sorry, u/misanthreddit – your comment has been removed for breaking Rule 1:&gt; **Direct responses to a CMV post must challenge at least one aspect of OP’s stated view (however minor), or ask a clarifying question**. Arguments in favor of the view OP is willing to change must be restricted to replies to other comments. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_1).  If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+1+Appeal+misanthreddit&amp;message=misanthreddit+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtq0f7u/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "[removed]", "I mean I&#039;d want to be him. He&#039;s rich and has some pretty awesome jobs.",
    "Sorry, u/tumblrloo – your comment has been removed for breaking Rule 1:&gt; **Direct responses to a CMV post must challenge at least one aspect of OP’s stated view (however minor), or ask a clarifying question**. Arguments in favor of the view OP is willing to change must be restricted to replies to other comments. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_1).  If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+1+Appeal+tumblrloo&amp;message=tumblrloo+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtpwvqi/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "I&#039;d say the main difference is Joe worked to get where he is, Kim and the gang are bizzarely famous to start with due to their father in the OJ trial.Another thing about Joe which you yourself brought up is that he really isn&#039;t that special in terms of either being a podcast host or hype man, or reality show star.Kim on the other hand is a bizzare enigma of a cultural icon status that can&#039;t be easily repeated. She by no means deserves it, but there can be hundreds of Joe rogans, there is only one Kim.",
    "I&#039;ve repeated this multiple times now. But it was more luck than anything that Rogan got to where he was. Anytime you get picked up for a TV show it&#039;s more luck than anything (not that he wasn&#039;t talented or didn&#039;t work hard, luck is just a much more significant factor in getting picked for a TV show)",
    "Fair enough, but out of other candidates for fear factor he was picked above others.Also you didn&#039;t seem to refute my second point which I think Is pretty solid for drawing a line between Joe and kim",
    "Joe Rogan is a stand up comedian first and foremost. That fact alone means he provides more to his fans than KKW. She&#039;s famous for being famous--he provides insightful views in his stand up. ",
    "If Kim Kardashian discussed interesting ideas all the time nobody would make fun of the show for being vapid. So it&#039;s not an apt comparison, even if people do partially listen to Joe Rogan because he&#039;s cool.",
    "If Joe&#039;s Kim Joey Coco Diaz is Kanye West. GTFOH dawg.", "[removed]",
    "Sorry, u/dadeblunts – your comment has been removed for breaking Rule 1:&gt; **Direct responses to a CMV post must challenge at least one aspect of OP’s stated view (however minor), or ask a clarifying question**. Arguments in favor of the view OP is willing to change must be restricted to replies to other comments. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_1).  If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+1+Appeal+dadeblunts&amp;message=dadeblunts+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtqhlbe/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).Sorry, u/dadeblunts – your comment has been removed for breaking Rule 5: &gt; **Comments must contribute meaningfully to the conversation**. Comments that are only jokes or &quot;written upvotes&quot; will be removed. Humor and affirmations of agreement can be contained within more substantial comments. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_5).If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+5+Appeal+dadeblunts&amp;message=dadeblunts+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtqhlbe/)+because...).",
    "[removed]",
    "Sorry, u/Thebuttdoctor – your comment has been removed for breaking Rule 1:&gt; **Direct responses to a CMV post must challenge at least one aspect of OP’s stated view (however minor), or ask a clarifying question**. Arguments in favor of the view OP is willing to change must be restricted to replies to other comments. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_1).  If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+1+Appeal+Thebuttdoctor&amp;message=Thebuttdoctor+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtqwig0/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "[removed]",
    "Sorry, u/Freethot_ – your comment has been removed for breaking Rule 1:&gt; **Direct responses to a CMV post must challenge at least one aspect of OP’s stated view (however minor), or ask a clarifying question**. Arguments in favor of the view OP is willing to change must be restricted to replies to other comments. [See the wiki page for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_1).  If you would like to appeal, [message the moderators by clicking this link](http://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview&amp;subject=Rule+1+Appeal+Freethot_&amp;message=Freethot_+would+like+to+appeal+the+removal+of+[his/her+post](https://www.reddit.com/r/changemyview/comments/7v6hu7/cmv_joe_rogan_is_kim_kardashian_for_guys/dtrczpl/)+because...). Please note that multiple violations will lead to a ban, as explained in our [moderation standards](https://www.reddit.com/r/changemyview/wiki/modstandards).",
    "More like Ellen.People actually like Ellen.Plus she&#039;s a talk show host.Plus they&#039;re both into chicks."]

single_test_document = " ".join(test_documents)

kingsman = "Another witty and fun, action film by Matthew Vaughn. " \
           "Taron Egerton and Colin Firth come together once more to recreate their fantastic spy duo. " \
           "Though the movie lacks in parts of what it promised in the trailers and details of what " \
           "many fans may have hoped. " \
           "It begrudgingly makes up for though its eye-popping visuals, " \
           "great new characters, and a clear believable storyline of Harry Hart's revival. Kingsman: " \
           "The Golden Circle is a near pitch perfect sequel to relive the entertainment of Kingsman: " \
           "The Secret Service."

text1 = "Hands down, of all the smartphones I have used so far, iPhone 8 Plus got the best battery life. I am not a " \
        "heavy user. All I do is make few quick calls, check emails, quick update of social media and maps and " \
        "navigation once in a while. On average with light use (excluding maps and navigation), iPhone 8 Plus lasts " \
        "for 4 full days! You heard it right, 4 full days! At the end of the 4th day, I am usually left with 5-10% of " \
        "battery and that's about the time I charge the phone. The heaviest I used it was once when I had to rely on " \
        "GPS for a full day. I started with 100% on the day I was travelling and by the end of the day, I had around " \
        "70% left. And I was able get through the next two days without any issues (light use only). "
text2 = "The last iPhone I used was an iPhone 5 and it is very clear that the smartphone cameras have come a long way. " \
        "iPhone 8 Plus produces very crisp photos without any over saturation, which is what I really appreciate. Even " \
        "though I got used to Samsung's over saturated photos over the last 3 years, whenever I see a photo true to " \
        "real life colours, it really appeals me. When buying this phone, my main concern with camera was its " \
        "performance in low light as I was used to pretty awesome performance on my Note 4. iPhone 8 Plus did not " \
        "disappoint me. I was able to capture some shots at a work function and they looked truly amazing. Auto HDR " \
        "seems very on point in my opinion. You will see these in the link below. Portrait mode has been somewhat " \
        "consistent. I felt that it does not perform as well on a very bright day. But overall, given that it is still " \
        "in beta, it works quite well (See Camaro SS photo). Video recording wise, it is pretty good at the standard " \
        "1080p 30fps. I am yet to try any 4k 60fps shots. But based on what I have seen from tech reviewers, " \
        "it is pretty awesome. "
text3 = "I have missed iOS a lot over the last 3 years and it feels good to be back. Super smooth and no hiccups. I " \
        "know few people have experienced some bugs recently. I guess I was one of the lucky ones not to have any " \
        "issues. Maybe it was already patched when I bought the phone. However, my only complaint is the fact that " \
        "iOS still does not let you clear all notifications from a particular app at once. I really would like to see " \
        "fixed in a future update. Customisation wise, I do not have any issues because I hardly customised my Note " \
        "4. Only widgets I had running were weather and calendar. Even then, I would still open up the actual app to " \
        "seek more detail. However, I still do not use iCloud. I really wish Apple would have given us more online " \
        "storage for backup. 5GB is hardly enough these days to backup everything on your phone. One of my mates " \
        "suggested that Apple should ship the phone with iCloud storage same as the phone. It surely would be " \
        "awesome. But business wise, I cannot see Apple going ahead with such a decision. But in my opinion, " \
        "iCloud users should get at least 15GB free. Coming from an Android, I thought it would make sense to keep " \
        "using my Google account to sync contacts and photos as it would take away the hassle of setting everything " \
        "up from scratch. Only issue is sometimes I feel like iOS restricting the background app refresh of Google " \
        "apps such as Google photos. For example, I always have to keep Google Photos running in order to allow " \
        "background upload, which makes no sense. Same goes for OneDrive. Overall, navigation around the OS is easy " \
        "and convenient. "

document3 = """
   Hands down, of all the smartphones I have used so far, iPhone 8 Plus got the best battery life. I am not a heavy user. 
   All I do is make few quick calls, check emails, quick update of social media and maps and navigation once in a while. 
   On average with light use (excluding maps and navigation), iPhone 8 Plus lasts for 4 full days! You heard it right, 
   4 full days! At the end of the 4th day, I am usually left with 5-10% of battery and that's about the time I charge the phone. 
   The heaviest I used it was once when I had to rely on GPS for a full day. I started with 100% on the day I was travelling and by the end of the day, 
   I had around 70% left. And I was able get through the next two days without any issues (light use only).

   The last iPhone I used was an iPhone 5 and it is very clear that the smartphone cameras have come a long way. 
   iPhone 8 Plus produces very crisp photos without any over saturation, which is what I really appreciate. 
   Even though I got used to Samsung's over saturated photos over the last 3 years, whenever I see a photo true to real life colours, 
   it really appeals me. When buying this phone, my main concern with camera was its performance in low light as I was used to pretty awesome 
   performance on my Note 4. iPhone 8 Plus did not disappoint me. I was able to capture some shots at a work function and they looked truly amazing. 
   Auto HDR seems very on point in my opinion. You will see these in the link below. Portrait mode has been somewhat consistent. 
   I felt that it does not perform as well on a very bright day. But overall, given that it is still in beta, it works quite well (See Camaro SS photo). 
   Video recording wise, it is pretty good at the standard 1080p 30fps. I am yet to try any 4k 60fps shots. But based on what I have seen from tech reviewers, 
   it is pretty awesome.

   For a LCD panel, iPhone 8 Plus display is great. Colours are accurate and it gets bright enough for outdoor use. Being a 1080p panel, 
   I think it really contributes to the awesome battery life that I have been experiencing. Talking about Touch ID, 
   I think it still is the most convenient way to unlock your phone and make any payments. For me personally, it works 99% of the time and in my experience, 
   it still is the benchmark of fingerprint unlocking of any given smartphone.

   I have missed iOS a lot over the last 3 years and it feels good to be back. Super smooth and no hiccups. 
   I know few people have experienced some bugs recently. I guess I was one of the lucky ones not to have any issues. 
   Maybe it was already patched when I bought the phone. However, 
   my only complaint is the fact that iOS still does not let you clear all notifications from a particular app at once. 
   I really would like to see fixed in a future update. Customisation wise, I do not have any issues because I hardly customised my Note 4. 
   Only widgets I had running were weather and calendar. Even then, I would still open up the actual app to seek more detail. However, 
   I still do not use iCloud. I really wish Apple would have given us more online storage for backup. 
   5GB is hardly enough these days to backup everything on your phone. One of my mates suggested that Apple should ship the phone with iCloud storage same as the phone. 
   It surely would be awesome. But business wise, I cannot see Apple going ahead with such a decision. But in my opinion, 
   iCloud users should get at least 15GB free. Coming from an Android, I thought it would make sense to keep using my Google account to 
   sync contacts and photos as it would take away the hassle of setting everything up from scratch. Only issue is sometimes I feel like 
   iOS restricting the background app refresh of Google apps such as Google photos. For example, I always have to keep Google Photos 
   running in order to allow "background upload", which makes no sense. Same goes for OneDrive. Overall, navigation around the OS is easy and convenient.

   I really think Apple Maps still needs lot of catching up. Over the last few weeks, I managed to use it couple of times. Navigation wise, it seem to 
   be good. But when it comes to looking up a place just by name seems like a real pain in the ass. Literally nothing shows up! Maybe it is a different 
   story in other countries. But for now, Google Maps is the number 1 on my list. 

   People seem to be complaining about Apple's decision to stick with the same design for 4 generations of phones. To be honest I quite adore this design. 
   It seems like a really timeless and well-aged design. The new glass back adds a little modern and polished look to the phone and it really helps grip 
   the phone if you are not using a case. Overall, iPhone 8 Plus is a great smartphone for every day use, especially with that killer battery life. 
   I do not really regret not getting an iPhone X, because in my opinion, first iteration will always be problematic. 8 Plus is the final iteration 
   of that particular design and have constantly improved. I am sure for my usage, the specs are more than enough to get me through the next 2-3 years.
   """

document1 = '''Iraqi vice president taha yassin ramadan announced today, sunday, that iraq refuses to back down from its
   decision to stop cooperating with disarmament inspectors before its demands are met. iraqi vice president taha yassin
   ramadan announced today, thursday, that iraq rejects cooperating with the united nations except on the issue of lifting 
   the blockade imposed upon it since the year 1990. Ramadan told reporters in baghdad that "iraq cannot deal positively 
   with whoever represents the security council unless there was a clear stance on the issue of lifting the blockade off 
   of it. Baghdad had decided late last october to completely cease cooperating with the inspectors of the united nations 
   special commision (unscom), in charge of disarming iraq's weapons, and whose work became very limited since the fifth 
   of august, and announced it will not resume its cooperation with the commission even if it were subjected to a military 
   operation. The russian foreign minister, igor ivanov, warned today, wednesday against using force against iraq, which 
   will destroy, according to him, seven years of difficult diplomatic work and will complicate the regional situation in 
   the area. Ivanov contended that carrying out air strikes against iraq, who refuses to cooperate with the united nations 
   inspectors, "will end the tremendous work achieved by the international group during the past seven years and will 
   complicate the situation in the region." Nevertheless, ivanov stressed that baghdad must resume working with the special 
   commission in charge of disarming the iraqi weapons of mass destruction (unscom). The special representative of the 
   united nations secretary-general in baghdad, prakash shah, announced today, wednesday, after meeting with the iraqi 
   deputy prime minister tariq aziz, that iraq refuses to back down from its decision to cut off cooperation with the 
   disarmament inspectors. British prime minister tony blair said today, sunday, that the crisis between the international 
   community and iraq "did not end" and that britain is still ready, prepared, and able to strike iraq." In a gathering 
   with the press held at the prime minister's office, blair contended that the crisis with iraq " will not end until iraq 
   has absolutely and unconditionally respected its commitments" towards the united nations. A spokesman for tony blair had
   indicated that the british prime minister gave permission to british air force tornado planes stationed to kuwait to 
   join the aerial bombardment against iraq.'''